# Generated by Django 2.2.3 on 2019-08-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.CharField(max_length=100)),
                ('pro_role', models.CharField(max_length=100)),
                ('pro_photo', models.ImageField(upload_to='images/%Y%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
            ],
        ),
    ]
