# Generated by Django 2.2.3 on 2019-08-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_logo', models.ImageField(upload_to='images/%Y/%m/%d/')),
            ],
        ),
    ]
